import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider ,SignIn,SignInButton,SignUp,SignedIn,SignedOut, UserButton} from "@clerk/nextjs";
import { User } from "@clerk/nextjs/server";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         <section className="h-screen w-screen flex flex-col items-center justify-center">
<SignedOut>
  <section className="h-screen w-screen flex flex-col items-center justify-center">
    <SignInButton></SignInButton>
  </section>
</SignedOut>

<SignedIn>
  {children}
</SignedIn>
        </section>
      </body>
    </html>
    </ClerkProvider> 
  );
}

